apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-persist-pvc
  namespace: opolo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2