apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-postgres-pvc
  namespace: opolo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
