apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-admin
spec:
  template:
    spec:
      containers:
      - name: portal-admin
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
