apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sift-persist-ingress
  namespace: opolo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "*.{{ .Values.domainName }}"
    http:
      paths:
      - path: /persist(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sift-persist
            port:
              number: 8091