apiVersion: apps/v1
kind: Deployment
metadata:
  name: sift-manage
spec:
  template:
    spec:
      containers:
      - name: sift-manage
        resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "1024Mi"
       