apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-source-test-framework
spec:
  template:
    spec:
      containers:
      - name: sift-datasource-data-source-test-framework
        env:
        - name: HEAP_SIZE
          value: 256m
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi